import "./beatPickers.cy";
import "./bpmKnob.cy";
import "./canvasPicker.cy";
import "./controllerPanel.cy";
import "./modal.cy";
import "./muteButton.cy";
import "./playButton.cy";
import "./switchBeatsChip.cy";
import "./tapChip.cy";
